from django.db import models

# Create your models here.
class Board(models.Model):
    b_no = models.AutoField(db_column='b_no', primary_key=True)
    b_title = models.CharField(db_column='b_title', max_length=255)
    b_note = models.TextField(db_column='b_note',)
    b_writer = models.CharField(db_column='b_writer', max_length=50)
    parent_no = models.IntegerField(db_column='parent_no', default=0)
    b_count = models.IntegerField(db_column='b_count',default=0)
    d_date = models.DateTimeField(db_column='d_date',)

    class Meta:
        managed = False
        db_table = 'board'

    def __str__(self):
        return "제목 :" + self.b_title + ", 작성자 :" + self.b_writer


#엑셀 데이터 스케쳐스 출고
# class ExcelData(models.Model):
#     UPDUSERCD1 = models.CharField(db_column='DLIVR_DECSN_OPRTO_CD', max_length=255)
#     SOKEY = models.CharField(db_column='DLIVR_NO', max_length=255)
#     DELIVERYCD = models.CharField(db_column='DELVR_CD', max_length=255)
#     ACTFLG = models.CharField(db_column='DLIVR_PRGRS_STTS_NM', max_length=255)
#     PICKBATCHKEY = models.CharField(db_column='BTCH_PRCES_NO', max_length=255)
#     ASSYKEY = models.CharField(db_column='ASSYKEY', max_length=255)
#     SOTYPE = models.CharField(db_column='DLIVR_TPE_SCTIN_NM', max_length=255)
#     STS = models.CharField(db_column='DLIVR_STTS_SCTIN_NM', max_length=255)
#     ORDERDATE = models.CharField(db_column='ORDER_DT', max_length=255)
#     DELIVNAME = models.CharField(db_column='RCRT_PHSPH_NM',  max_length=255)
#     SHIPSCHDATE = models.CharField(db_column='DLIVR_PRRRG_DT', max_length=255)
#     SHIPDATE = models.CharField(db_column='DLIVR_CMPLE_DT', max_length=255)
#     PRIORITIES = models.CharField(db_column='DLIVR_ORER', max_length=255)
#     OWNERCD = models.CharField(db_column='OWR_CD', max_length=255)
#     ITEMCD = models.CharField(db_column='PRLST_CD', max_length=255)
#     EXPECTQTY1 = models.CharField(db_column='DLIVR_PRRRG_QNTT', max_length=255)
#     SHIPPEDQTY1 = models.CharField(db_column='DLIVR_CMPLE_QNTT', max_length=255)
#     CUSTOMERCD = models.CharField(db_column='BSCNN_CD', max_length=255)
#     OWNERNM = models.CharField(db_column='OWR_NM', max_length=255)
#     ORDERTYPE = models.CharField(db_column='ORDER_TPE_SCTIN_NM', max_length=255)
#     DELIVSCHDATE = models.CharField(db_column='DELIVSCHDATE', max_length=255)
#     DELIVDATE = models.CharField(db_column='DELIVDATE', max_length=255)
#     TRANSPORTPRIORITY = models.CharField(db_column='TRANSPORTPRIORITY', max_length=255)
#     WAREHOUSECD = models.CharField(db_column='WRHS_CD', max_length=255)
#     OTHERREFNO3 = models.CharField(db_column='DT_ACTO_STRE_DLIVR_NO', max_length=255)
#     WAREHOUSENM = models.CharField(db_column='DLIVR_WRHS_NM', max_length=255)
#     PREKEY = models.CharField(db_column='SHPMN_DIRCT_NO', max_length=255)
#     CUSTOMERNM = models.CharField(db_column='BSCNN_NM', max_length=255)
#     SHIPTOCD = models.CharField(db_column='DLGDS_OFFCE_CD', max_length=255)
#     SHIPTONM = models.CharField(db_column='DLGDS_OFFCE_NM', max_length=255)
#     ADDRESS1 = models.CharField(db_column='DLGDS_OFFCE_BSS_ADDR', max_length=255)
#     ADDRESS2 = models.CharField(db_column='ADDRESS2', max_length=255)
#     POSTNO1 = models.CharField(db_column='POST_NO', max_length=255)
#     POSTNO2 = models.CharField(db_column='POSTNO2', max_length=255)
#     HPNO = models.CharField(db_column='PINCH_MTLNO', max_length=255)
#     EMAIL = models.CharField(db_column='PINCH_EMAIL', max_length=255)
#     REFNAME = models.CharField(db_column='BSCNN_RFRNC_NM', max_length=255)
#     ALLOCGROUP = models.CharField(db_column='ALLOCGROUP', max_length=255)
#     NOTES = models.CharField(db_column='RMRK', max_length=255)
#     OTHERREFNO1 = models.CharField(db_column='OTHERREFNO1', max_length=255)
#     OTHERREFNO2 = models.CharField(db_column='OTHERREFNO2', max_length=255)
#     MOVEKEY = models.CharField(db_column='MOVEKEY', max_length=255)
#     WBKEY = models.CharField(db_column='TRNSO_HEADR_NO', max_length=255)
#     ADDDATETIME = models.CharField(db_column='DLIVR_ORDER_CRTIN_DTM', max_length=255)
#     ADDUSERCD = models.CharField(db_column='DLIVR_RGTER_ID', max_length=255)
#     UPDDATETIME = models.CharField(db_column='DLIVR_UPDT_DTM', max_length=255)
#     UPDUSERCD = models.CharField(db_column='DLIVR_UPUSR_CD', max_length=255)
#     TERMINALCD = models.CharField(db_column='DLIVR_OPRTO_PC_CD', max_length=255)
#     ORDERCUSTNAME = models.CharField(db_column='ORDERCUSTNAME', max_length=255)
#     ORDERCUSTPHONE = models.CharField(db_column='ORDERCUSTPHONE', max_length=255)
#     ORDERCUSTHP = models.CharField(db_column='ORDERCUSTHP', max_length=255)
#     PHONENO = models.CharField(db_column='PHONENO', max_length=255)
#     SOKEY1 = models.CharField(db_column='SOKEY1', max_length=255)
#     SOLINENO = models.CharField(db_column='SOLINENO', max_length=255)
#     ORDERKEY = models.CharField(db_column='ORDERKEY', max_length=255)
#     ORDERLINENO = models.CharField(db_column='ORDERLINENO', max_length=255)
#     ITEMGROUP = models.CharField(db_column='ITEMGROUP', max_length=255)
#     IFITEMCD = models.CharField(db_column='PRLST_BRCD_NO', max_length=255)
#     LOT1 = models.CharField(db_column='LOT1', max_length=255)
#     LOT2 = models.CharField(db_column='LOT2', max_length=255)
#     LOT3 = models.CharField(db_column='LOT3', max_length=255)
#     LOT4 = models.CharField(db_column='LOT4', max_length=255)
#     LOT5 = models.CharField(db_column='LOT5', max_length=255)
#     NOSHIPPINGFLG = models.CharField(db_column='NOSHIPPINGFLG', max_length=255)
#     OTHERFLG = models.CharField(db_column='OTHERFLG', max_length=255)
#     XDOCKQTY1 = models.CharField(db_column='XDOCKQTY1', max_length=255)
#     ALLOCQTY1 = models.CharField(db_column='ALLOCQTY1', max_length=255)
#     PICKEDQTY1 = models.CharField(db_column='PICKEDQTY1', max_length=255)
#     SORTEDQTY1 = models.CharField(db_column='SORTEDQTY1', max_length=255)
#     ADJUSTQTY1 = models.CharField(db_column='DLIVR_CNCLL_QNTT', max_length=255)
#     PRICE1 = models.CharField(db_column='SAL_UNPRC_AMT', max_length=255)
#     PRICE2 = models.CharField(db_column='SAL_AMT', max_length=255)
#     PRICE3 = models.CharField(db_column='VAT', max_length=255)
#     NOTES1 = models.CharField(db_column='GOODS_RMRK', max_length=255)
#     LOTRESERVEFLG = models.CharField(db_column='INVNR_LCK_CONT', max_length=255)
#     PICKQTYERRORFLG = models.CharField(db_column='LOTRESERVEFLG', max_length=255)
#     XDOCFLG = models.CharField(db_column='XDOCFLG', max_length=255)
#     MOVELINENO = models.CharField(db_column='MOVELINENO', max_length=255)
#     ASSYLINENO = models.CharField(db_column='ASSYLINENO', max_length=255)
#     ADDDATETIME1 = models.CharField(db_column='DLIVR_RGSTN_DTM', max_length=255)
#     ADDUSERCD1 = models.CharField(db_column='DLIVR_RGTER_ID_1', max_length=255)
#     UPDDATETIME1 = models.CharField(db_column='DLIVR_PRCES_NO', max_length=255)
#     TERMINALCD1 = models.CharField(db_column='DLIVR_OPRTO_PC_CD_1', max_length=255)
#     SHOPITEMCD = models.CharField(db_column='SHOPITEMCD', max_length=255)
#     OTHERVALUE1 = models.CharField(db_column='OTHERVALUE1', max_length=255)
#     OTHERVALUE2 = models.CharField(db_column='OTHERVALUE2', max_length=255)
#     FAX1 = models.CharField(db_column='FAX1', max_length=255)
#     CONFIRMQTY = models.CharField(db_column='CONFIRMQTY', max_length=255)
#     NAME = models.CharField(db_column='PRLST_NM', max_length=255)
#     CONDATE = models.CharField(db_column='CONDATE', max_length=255)
#     CRUD = models.CharField(db_column='DLIVR_PRCES_STTS_CD', max_length=255)
#     SODAY = models.CharField(db_column='CTDL_DELAY_DCNT', max_length=255)
#     IFDATE = models.CharField(db_column='IFDATE', max_length=255)
#     IFSODAY = models.CharField(db_column='CMPTN_DLIVR_PRCES_DELAY_DCNT', max_length=255)
#     id = models.AutoField(db_column='id', primary_key=True)

#     class Meta:
#         managed = False
#         db_table = 'tb_en_skx_dlivr_stats_s_02'

#     def __str__(self):
#         return "UPDUSERCD1 :" + self.UPDUSERCD1 + ", SOKEY :" + self.SOKEY
class ExcelData(models.Model):
    dlivr_decsn_oprto_cd=models.CharField(db_column='dlivr_decsn_oprto_cd', max_length=255)
    dlivr_no=models.CharField(db_column='dlivr_no', max_length=255)
    delvr_cd=models.CharField(db_column='delvr_cd', max_length=255)
    dlivr_prgrs_stts_nm=models.CharField(db_column='dlivr_prgrs_stts_nm', max_length=255)
    btch_prces_no=models.CharField(db_column='btch_prces_no', max_length=255)
    sppm_key_no=models.CharField(db_column='sppm_key_no', max_length=255)
    dlivr_tpe_sctin_nm=models.CharField(db_column='dlivr_tpe_sctin_nm', max_length=255)
    dlivr_stts_sctin_nm=models.CharField(db_column='dlivr_stts_sctin_nm', max_length=255)
    order_dtm=models.CharField(db_column='order_dtm', max_length=255)
    rcrt_phsph_nm=models.CharField(db_column='rcrt_phsph_nm', max_length=255)
    dlivr_prrrg_dtm=models.CharField(db_column='dlivr_prrrg_dtm', max_length=255)
    dlivr_cmple_dtm=models.CharField(db_column='dlivr_cmple_dtm', max_length=255)
    dlivr_orer=models.CharField(db_column='dlivr_orer', max_length=255)
    owr_cd=models.CharField(db_column='owr_cd', max_length=255)
    prlst_cd=models.CharField(db_column='prlst_cd', max_length=255)
    dlivr_prrrg_qntt=models.CharField(db_column='dlivr_prrrg_qntt', max_length=255)
    dlivr_cmple_qntt=models.CharField(db_column='dlivr_cmple_qntt', max_length=255)
    bscnn_cd=models.CharField(db_column='bscnn_cd', max_length=255)
    owr_nm=models.CharField(db_column='owr_nm', max_length=255)
    order_tpe_sctin_nm=models.CharField(db_column='order_tpe_sctin_nm', max_length=255)
    delvr_prrrg_dtm=models.CharField(db_column='delvr_prrrg_dtm', max_length=255)
    delvr_dtm=models.CharField(db_column='delvr_dtm', max_length=255)
    delvr_prrt=models.CharField(db_column='delvr_prrt', max_length=255)
    wrhs_cd=models.CharField(db_column='wrhs_cd', max_length=255)
    dt_acto_stre_dlivr_no=models.CharField(db_column='dt_acto_stre_dlivr_no', max_length=255)
    dlivr_wrhs_nm=models.CharField(db_column='dlivr_wrhs_nm', max_length=255)
    shpmn_dirct_no=models.CharField(db_column='shpmn_dirct_no', max_length=255)
    bscnn_nm=models.CharField(db_column='bscnn_nm', max_length=255)
    dlgds_offce_cd=models.CharField(db_column='dlgds_offce_cd', max_length=255)
    dlgds_offce_nm=models.CharField(db_column='dlgds_offce_nm', max_length=255)
    dlgds_offce_bss_addr=models.CharField(db_column='dlgds_offce_bss_addr', max_length=255)
    rcrt_phsph_dtadd=models.CharField(db_column='rcrt_phsph_dtadd', max_length=255)
    post_no=models.CharField(db_column='post_no', max_length=255)
    postno2=models.CharField(db_column='postno2', max_length=255)
    pinch_mtlno=models.CharField(db_column='pinch_mtlno', max_length=255)
    pinch_email=models.CharField(db_column='pinch_email', max_length=255)
    bscnn_rfrnc_nm=models.CharField(db_column='bscnn_rfrnc_nm', max_length=255)
    assgn_group_nm=models.CharField(db_column='assgn_group_nm', max_length=255)
    rmrk=models.CharField(db_column='rmrk', max_length=255)
    etc_mtter1=models.CharField(db_column='etc_mtter1', max_length=255)
    etc_mtter2=models.CharField(db_column='etc_mtter2', max_length=255)
    mvmnt_key_no=models.CharField(db_column='mvmnt_key_no', max_length=255)
    trnso_headr_no=models.CharField(db_column='trnso_headr_no', max_length=255)
    dlivr_order_crtin_dtm=models.CharField(db_column='dlivr_order_crtin_dtm', max_length=255)
    dlivr_rgter_id1=models.CharField(db_column='dlivr_rgter_id1', max_length=255)
    dlivr_updt_dtm=models.CharField(db_column='dlivr_updt_dtm', max_length=255)
    dlivr_upusr_cd=models.CharField(db_column='dlivr_upusr_cd', max_length=255)
    dlivr_oprto_pc_cd1=models.CharField(db_column='dlivr_oprto_pc_cd1', max_length=255)
    order_cstmr_nm=models.CharField(db_column='order_cstmr_nm', max_length=255)
    order_cstmr_tlno=models.CharField(db_column='order_cstmr_tlno', max_length=255)
    order_cstmr_mtlno=models.CharField(db_column='order_cstmr_mtlno', max_length=255)
    rcrt_phsph_tlno=models.CharField(db_column='rcrt_phsph_tlno', max_length=255)
    clssc_key_no=models.CharField(db_column='clssc_key_no', max_length=255)
    clssc_lne_no=models.CharField(db_column='clssc_lne_no', max_length=255)
    order_key_no=models.CharField(db_column='order_key_no', max_length=255)
    order_lne_no=models.CharField(db_column='order_lne_no', max_length=255)
    prlst_group_cd=models.CharField(db_column='prlst_group_cd', max_length=255)
    prlst_brcd_no=models.CharField(db_column='prlst_brcd_no', max_length=255)
    lt_attrb_nm1=models.CharField(db_column='lt_attrb_nm1', max_length=255)
    lt_attrb_nm2=models.CharField(db_column='lt_attrb_nm2', max_length=255)
    lt_attrb_nm3=models.CharField(db_column='lt_attrb_nm3', max_length=255)
    lt_attrb_nm4=models.CharField(db_column='lt_attrb_nm4', max_length=255)
    lt_attrb_nm5=models.CharField(db_column='lt_attrb_nm5', max_length=255)
    un_ldng_sctin_val=models.CharField(db_column='un_ldng_sctin_val', max_length=255)
    etc_sctin_val=models.CharField(db_column='etc_sctin_val', max_length=255)
    crsdk_qntt=models.CharField(db_column='crsdk_qntt', max_length=255)
    assgn_qntt=models.CharField(db_column='assgn_qntt', max_length=255)
    pckn_qntt=models.CharField(db_column='pckn_qntt', max_length=255)
    clssc_qntt=models.CharField(db_column='clssc_qntt', max_length=255)
    dlivr_cncll_qntt=models.CharField(db_column='dlivr_cncll_qntt', max_length=255)
    sal_unprc_amt=models.CharField(db_column='sal_unprc_amt', max_length=255)
    sal_amt=models.CharField(db_column='sal_amt', max_length=255)
    vat=models.CharField(db_column='vat', max_length=255)
    goods_rmrk=models.CharField(db_column='goods_rmrk', max_length=255)
    invnr_lck_cont=models.CharField(db_column='invnr_lck_cont', max_length=255)
    lt_rsrvt_sctin_cont=models.CharField(db_column='lt_rsrvt_sctin_cont', max_length=255)
    crsdk_sctin_val=models.CharField(db_column='crsdk_sctin_val', max_length=255)
    mvmnt_lne_no=models.CharField(db_column='mvmnt_lne_no', max_length=255)
    sppm_lne_no=models.CharField(db_column='sppm_lne_no', max_length=255)
    dlivr_rgstn_dtm=models.CharField(db_column='dlivr_rgstn_dtm', max_length=255)
    dlivr_rgter_id2=models.CharField(db_column='dlivr_rgter_id2', max_length=255)
    dlivr_prces_dtm=models.CharField(db_column='dlivr_prces_dtm', max_length=255)
    dlivr_oprto_pc_cd2=models.CharField(db_column='dlivr_oprto_pc_cd2', max_length=255)
    spml_prlst_no=models.CharField(db_column='spml_prlst_no', max_length=255)
    ordno1=models.CharField(db_column='ordno1', max_length=255)
    ordno2=models.CharField(db_column='ordno2', max_length=255)
    rcrt_phsph_fxno=models.CharField(db_column='rcrt_phsph_fxno', max_length=255)
    decsn_qntt=models.CharField(db_column='decsn_qntt', max_length=255)
    prlst_nm=models.CharField(db_column='prlst_nm', max_length=255)
    dlivr_decsn_dtm=models.CharField(db_column='dlivr_decsn_dtm', max_length=255)
    dlivr_prces_stts_cd=models.CharField(db_column='dlivr_prces_stts_cd', max_length=255)
    ctdl_delay_dcnt=models.CharField(db_column='ctdl_delay_dcnt', max_length=255)
    bscnn_dlivr_rcipt_dtm=models.CharField(db_column='bscnn_dlivr_rcipt_dtm', max_length=255)
    cmptn_dlivr_prces_delay_dcnt=models.CharField(db_column='cmptn_dlivr_prces_delay_dcnt', max_length=255)
    id = models.AutoField(db_column='id', primary_key=True)

    class Meta:
        managed = False
        db_table = 'tb_en_skx_dlivr_stats_s_02'

    def __str__(self):
        # return "UPDUSERCD1 :" + self.UPDUSERCD1 + ", SOKEY :" + self.SOKEY
        return "dlivr_decsn_oprto_cd :" + self.dlivr_decsn_oprto_cd + ", dlivr_no :" + self.dlivr_no


#엑셀 데이터 쏨니아 출고
# class ExcelDataSomExe(models.Model):
#     PRIORITIES = models.CharField(db_column='PRIORITIES', max_length=255)
#     SOKEY = models.CharField(db_column='SOKEY', max_length=255)
#     PREKEY = models.CharField(db_column='PREKEY', max_length=255)
#     OTHERVALUE1 = models.CharField(db_column='OTHERVALUE1', max_length=255)
#     WAYBILLNO = models.CharField(db_column='WAYBILLNO', max_length=255)
#     MESSAGE = models.CharField(db_column='MESSAGE', max_length=255)
#     SOTYPE = models.CharField(db_column='SOTYPE', max_length=255)
#     STS = models.CharField(db_column='STS', max_length=255)
#     ACTFLG = models.CharField(db_column='ACTFLG', max_length=255)
#     OWNERCD = models.CharField(db_column='OWNERCD',  max_length=255)
#     ORDERDATE = models.CharField(db_column='ORDERDATE', max_length=255)
#     SHIPDATE = models.CharField(db_column='SHIPDATE', max_length=255)
#     SHIPSCHDATE = models.CharField(db_column='SHIPSCHDATE', max_length=255)
#     CUSTOMERCD = models.CharField(db_column='CUSTOMERCD', max_length=255)
#     ORDERTYPE = models.CharField(db_column='ORDERTYPE', max_length=255)
#     DELIVNAME = models.CharField(db_column='DELIVNAME', max_length=255)
#     ADDRESS1 = models.CharField(db_column='ADDRESS1', max_length=255)
#     POSTNO = models.CharField(db_column='POSTNO', max_length=255)
#     ADDRESS2 = models.CharField(db_column='ADDRESS2', max_length=255)
#     PHONENO = models.CharField(db_column='PHONENO', max_length=255)
#     FAX1 = models.CharField(db_column='FAX1', max_length=255)
#     EMAIL = models.CharField(db_column='EMAIL', max_length=255)
#     REFNAME = models.CharField(db_column='REFNAME', max_length=255)
#     CUSTOMERNM = models.CharField(db_column='CUSTOMERNM', max_length=255)
#     OWNERNM = models.CharField(db_column='OWNERNM', max_length=255)
#     ALLOCGROUP = models.CharField(db_column='ALLOCGROUP', max_length=255)
#     NOTES = models.CharField(db_column='NOTES', max_length=255)
#     OTHERREFNO2 = models.CharField(db_column='OTHERREFNO2', max_length=255)
#     OTHERREFNO3 = models.CharField(db_column='OTHERREFNO3', max_length=255)
#     PICKBATCHKEY = models.CharField(db_column='PICKBATCHKEY', max_length=255)
#     MOVEKEY = models.CharField(db_column='MOVEKEY', max_length=255)
#     ASSYKEY = models.CharField(db_column='ASSYKEY', max_length=255)
#     NAME = models.CharField(db_column='NAME', max_length=255)
#     ADDDATETIME = models.CharField(db_column='ADDDATETIME', max_length=255)
#     ADDUSERCD = models.CharField(db_column='ADDUSERCD', max_length=255)
#     UPDDATETIME = models.CharField(db_column='UPDDATETIME', max_length=255)
#     UPDUSERCD = models.CharField(db_column='UPDUSERCD', max_length=255)
#     ORDERCUSTNAME = models.CharField(db_column='ORDERCUSTNAME', max_length=255)
#     ORDERCUSTPHONE = models.CharField(db_column='ORDERCUSTPHONE', max_length=255)
#     ORDERCUSTHP = models.CharField(db_column='ORDERCUSTHP', max_length=255)
#     HPNO = models.CharField(db_column='HPNO', max_length=255)
#     SOKEY1 = models.CharField(db_column='SOKEY1', max_length=255)
#     IFITEMCD = models.CharField(db_column='IFITEMCD', max_length=255)
#     SOLINENO = models.CharField(db_column='SOLINENO', max_length=255)
#     PICKQTYERRORFLG = models.CharField(db_column='PICKQTYERRORFLG', max_length=255)
#     ITEMCD = models.CharField(db_column='ITEMCD', max_length=255)
#     LOT1 = models.CharField(db_column='LOT1', max_length=255)
#     LOT2 = models.CharField(db_column='LOT2', max_length=255)
#     LOT3 = models.CharField(db_column='LOT3', max_length=255)
#     EXPECTQTY1 = models.CharField(db_column='EXPECTQTY1', max_length=255)
#     LOT5 = models.CharField(db_column='LOT5', max_length=255)
#     NOSHIPPINGFLG = models.CharField(db_column='NOSHIPPINGFLG', max_length=255)
#     SHIPPEDOTY1 = models.CharField(db_column='SHIPPEDOTY1', max_length=255)
#     ADJUSTOTY1 = models.CharField(db_column='ADJUSTOTY1', max_length=255)
#     OTHERFLG = models.CharField(db_column='OTHERFLG', max_length=255)
#     XDOCKQTY1 = models.CharField(db_column='XDOCKQTY1', max_length=255)
#     PICKEDOTY1 = models.CharField(db_column='PICKEDOTY1', max_length=255)
#     ALLOCQTY1 = models.CharField(db_column='ALLOCQTY1', max_length=255)
#     SORTEDQTY1 = models.CharField(db_column='SORTEDQTY1', max_length=255)
#     PRICE2 = models.CharField(db_column='PRICE2', max_length=255)
#     PRICE3 = models.CharField(db_column='PRICE3', max_length=255)
#     NOTES1 = models.CharField(db_column='NOTES1', max_length=255)
#     LOTRESERVEFLG = models.CharField(db_column='LOTRESERVEFLG', max_length=255)
#     XDOCFLG = models.CharField(db_column='XDOCFLG', max_length=255)
#     MOVELINENO = models.CharField(db_column='MOVELINENO', max_length=255)
#     ASSYLINENO = models.CharField(db_column='ASSYLINENO', max_length=255)
#     ADDDATETIME1 = models.CharField(db_column='ADDDATETIME1', max_length=255)
#     ADDUSERCD1 = models.CharField(db_column='ADDUSERCD1', max_length=255)
#     UPDDATETIME1 = models.CharField(db_column='UPDDATETIME1', max_length=255)
#     UPDUSERCD1 = models.CharField(db_column='UPDUSERCD1', max_length=255)
#     TERMINALCD1 = models.CharField(db_column='TERMINALCD1', max_length=255)
#     SHOPITEMCD = models.CharField(db_column='SHOPITEMCD', max_length=255)
#     OTHERVALUE2 = models.CharField(db_column='OTHERVALUE2', max_length=255)
#     CONFIRMQTY = models.CharField(db_column='CONFIRMQTY', max_length=255)
#     MANUITEMCD = models.CharField(db_column='MANUITEMCD', max_length=255)
#     CONDATE = models.CharField(db_column='CONDATE', max_length=255)
#     CRUD = models.CharField(db_column='CRUD', max_length=255)
#     CATEGORY2 = models.CharField(db_column='CATEGORY2', max_length=255)
#     CATEGORY5 = models.CharField(db_column='CATEGORY5', max_length=255)
#     ITEM_GUBUN = models.CharField(db_column='ITEM_GUBUN', max_length=255)
#     ITEM_BOGJONG = models.CharField(db_column='ITEM_BOGJONG', max_length=255)
#     id = models.AutoField(db_column='id', primary_key=True)

#     class Meta:
#         managed = False
#         db_table = 'tb_en_skx_rtgds_stats_s_02'

#     def __str__(self):
#         return "UPDUSERCD1 :" 
class ExcelDataSomExe(models.Model):
    dlivr_orer=models.CharField(db_column='dlivr_orer', max_length=255)
    dlivr_no=models.CharField(db_column='dlivr_no', max_length=255)
    ordno=models.CharField(db_column='ordno', max_length=255)
    order_prlst_no=models.CharField(db_column='order_prlst_no', max_length=255)
    trnso_headr_no=models.CharField(db_column='trnso_headr_no', max_length=255)
    mssg_cont=models.CharField(db_column='mssg_cont', max_length=255)
    dlivr_tpe_sctin_nm=models.CharField(db_column='dlivr_tpe_sctin_nm', max_length=255)
    dlivr_stts_sctin_nm=models.CharField(db_column='dlivr_stts_sctin_nm', max_length=255)
    dlivr_prgrs_stts_nm=models.CharField(db_column='dlivr_prgrs_stts_nm', max_length=255)
    owr_cd=models.CharField(db_column='owr_cd', max_length=255)
    order_dtm=models.CharField(db_column='order_dtm', max_length=255)
    dlivr_cmple_dtm=models.CharField(db_column='dlivr_cmple_dtm', max_length=255)
    dlivr_prrrg_dtm=models.CharField(db_column='dlivr_prrrg_dtm', max_length=255)
    bscnn_cd=models.CharField(db_column='bscnn_cd', max_length=255)
    order_tpe_sctin_nm=models.CharField(db_column='order_tpe_sctin_nm', max_length=255)
    rcrt_phsph_nm=models.CharField(db_column='rcrt_phsph_nm', max_length=255)
    rcrt_phsph_bss_addr=models.CharField(db_column='rcrt_phsph_bss_addr', max_length=255)
    post_no=models.CharField(db_column='post_no', max_length=255)
    rcrt_phsph_dtadd=models.CharField(db_column='rcrt_phsph_dtadd', max_length=255)
    rcrt_phsph_tlno=models.CharField(db_column='rcrt_phsph_tlno', max_length=255)
    rcrt_phsph_fxno=models.CharField(db_column='rcrt_phsph_fxno', max_length=255)
    rcrt_phsph_email=models.CharField(db_column='rcrt_phsph_email', max_length=255)
    bscnn_rfrnc_nm=models.CharField(db_column='bscnn_rfrnc_nm', max_length=255)
    rcrt_phsph_stre_nm=models.CharField(db_column='rcrt_phsph_stre_nm', max_length=255)
    owr_nm=models.CharField(db_column='owr_nm', max_length=255)
    assgn_group_nm=models.CharField(db_column='assgn_group_nm', max_length=255)
    rmrk=models.CharField(db_column='rmrk', max_length=255)
    sal_cos_sctin_cd=models.CharField(db_column='sal_cos_sctin_cd', max_length=255)
    dt_acto_stre_dlivr_no=models.CharField(db_column='dt_acto_stre_dlivr_no', max_length=255)
    pckn_dirct_no=models.CharField(db_column='pckn_dirct_no', max_length=255)
    mvmnt_key_no=models.CharField(db_column='mvmnt_key_no', max_length=255)
    sppm_key_no=models.CharField(db_column='sppm_key_no', max_length=255)
    prlst_nm=models.CharField(db_column='prlst_nm', max_length=255)
    dlivr_order_crtin_dtm=models.CharField(db_column='dlivr_order_crtin_dtm', max_length=255)
    dlivr_rgter_id1=models.CharField(db_column='dlivr_rgter_id1', max_length=255)
    dlivr_updt_dtm=models.CharField(db_column='dlivr_updt_dtm', max_length=255)
    dlivr_upusr_cd=models.CharField(db_column='dlivr_upusr_cd', max_length=255)
    ordrr_nm=models.CharField(db_column='ordrr_nm', max_length=255)
    ordrr_tlno=models.CharField(db_column='ordrr_tlno', max_length=255)
    ordrr_mtlno=models.CharField(db_column='ordrr_mtlno', max_length=255)
    pinch_mtlno=models.CharField(db_column='pinch_mtlno', max_length=255)
    clssc_key_no=models.CharField(db_column='clssc_key_no', max_length=255)
    brcd_no=models.CharField(db_column='brcd_no', max_length=255)
    clssc_lne_no=models.CharField(db_column='clssc_lne_no', max_length=255)
    invnr_lck_cont=models.CharField(db_column='invnr_lck_cont', max_length=255)
    prlst_cd=models.CharField(db_column='prlst_cd', max_length=255)
    lt_attrb_nm1=models.CharField(db_column='lt_attrb_nm1', max_length=255)
    lt_attrb_nm2=models.CharField(db_column='lt_attrb_nm2', max_length=255)
    lt_attrb_nm3=models.CharField(db_column='lt_attrb_nm3', max_length=255)
    dlivr_prrrg_qntt=models.CharField(db_column='dlivr_prrrg_qntt', max_length=255)
    lt_attrb_nm5=models.CharField(db_column='lt_attrb_nm5', max_length=255)
    un_ldng_sctin_val=models.CharField(db_column='un_ldng_sctin_val', max_length=255)
    dlivr_cmple_qntt=models.CharField(db_column='dlivr_cmple_qntt', max_length=255)
    dlivr_cncll_qntt=models.CharField(db_column='dlivr_cncll_qntt', max_length=255)
    etc_sctin_val=models.CharField(db_column='etc_sctin_val', max_length=255)
    crsdk_qntt=models.CharField(db_column='crsdk_qntt', max_length=255)
    pckn_qntt=models.CharField(db_column='pckn_qntt', max_length=255)
    assgn_qntt=models.CharField(db_column='assgn_qntt', max_length=255)
    clssc_qntt=models.CharField(db_column='clssc_qntt', max_length=255)
    sal_amt=models.CharField(db_column='sal_amt', max_length=255)
    vat=models.CharField(db_column='vat', max_length=255)
    goods_rmrk=models.CharField(db_column='goods_rmrk', max_length=255)
    lt_rsrvt_sctin_cont=models.CharField(db_column='lt_rsrvt_sctin_cont', max_length=255)
    crsdk_sctin_val=models.CharField(db_column='crsdk_sctin_val', max_length=255)
    mvmnt_lne_no=models.CharField(db_column='mvmnt_lne_no', max_length=255)
    sppm_lne_no=models.CharField(db_column='sppm_lne_no', max_length=255)
    dlivr_rgstn_dtm=models.CharField(db_column='dlivr_rgstn_dtm', max_length=255)
    dlivr_rgter_id2=models.CharField(db_column='dlivr_rgter_id2', max_length=255)
    dlivr_prces_dtm=models.CharField(db_column='dlivr_prces_dtm', max_length=255)
    dlivr_decsn_oprto_cd=models.CharField(db_column='dlivr_decsn_oprto_cd', max_length=255)
    dlivr_oprto_pc_cd=models.CharField(db_column='dlivr_oprto_pc_cd', max_length=255)
    spml_prlst_no=models.CharField(db_column='spml_prlst_no', max_length=255)
    cstmr_pdnr_no=models.CharField(db_column='cstmr_pdnr_no', max_length=255)
    decsn_qntt=models.CharField(db_column='decsn_qntt', max_length=255)
    mkr_prduc_cd=models.CharField(db_column='mkr_prduc_cd', max_length=255)
    dlivr_decsn_dtm=models.CharField(db_column='dlivr_decsn_dtm', max_length=255)
    dlivr_prces_stts_cd=models.CharField(db_column='dlivr_prces_stts_cd', max_length=255)
    ctgry_cont=models.CharField(db_column='ctgry_cont', max_length=255)
    color_cd=models.CharField(db_column='color_cd', max_length=255)
    prdct_sctin_nm=models.CharField(db_column='prdct_sctin_nm', max_length=255)
    prduc_ctgry_sctin_nm=models.CharField(db_column='prduc_ctgry_sctin_nm', max_length=255)
    id = models.AutoField(db_column='id', primary_key=True)
    class Meta:
        managed = False
        db_table = 'tb_en_som_rtgds_stats_s_02'
        
    def __str__(self):
        # return "updusercd1 :"
        return "dlivr_decsn_oprto_cd :" 